### ISSUE TITLE
Issue with cyanite-prune

### ISSUE THREAD

**Issue by jippi** [WrathOfChris/cyanite-utils#15]
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.8 (wheezy)
Release:	7.8
Codename:	wheezy

Python 2.7.3

pip 1.1 from /usr/lib/python2.7/dist-packages (python 2.7)

Cyanite config:

````
carbon:
  host: "127.0.0.1"
  port: 2003
  rollups:
    - 1m:90d
    - 5m:1y
    - 15m:5y

http:
  host: "0.0.0.0"
  port: 8081

logging:
  level: info
  console: true
  files:
    - "/tmp/cyanite.log"

store:
  cluster: "cassandra.service.bownty"
  keyspace: 'metric'
  chan_size: 10000
  batch_size: 500

```

output

```
root @ graphite [ ~ ] [ 08:48:26 ]
-> cyanite-list | cyanite-prune | cyanite-delete
Traceback (most recent call last):
  File "/usr/local/bin/cyanite-prune", line 9, in <module>
    load_entry_point('cyanite-utils==0.0.11', 'console_scripts', 'cyanite-prune')()
  File "/usr/local/lib/python2.7/dist-packages/cyanite_utils/cli.py", line 87, in cyanite_prune
    metrics = CyaniteMetrics(config)
  File "/usr/local/lib/python2.7/dist-packages/cyanite_utils/CyaniteMetrics.py", line 21, in __init__
    for (rollup, interval) in self.config.rollups():
  File "/usr/local/lib/python2.7/dist-packages/cyanite_utils/Config.py", line 63, in rollups
    rollups.append((r['period'], r['rollup']))
TypeError: string indices must be integers, not str
Traceback (most recent call last):
  File "/usr/local/bin/cyanite-list", line 9, in <module>
    load_entry_point('cyanite-utils==0.0.11', 'console_scripts', 'cyanite-list')()
  File "/usr/local/lib/python2.7/dist-packages/cyanite_utils/cli.py", line 29, in cyanite_list
    paths.printpaths('*')
  File "/usr/local/lib/python2.7/dist-packages/cyanite_utils/CyanitePaths.py", line 50, in printpaths
    self.printpaths("%s.*" % path['path'])
  File "/usr/local/lib/python2.7/dist-packages/cyanite_utils/CyanitePaths.py", line 50, in printpaths
    self.printpaths("%s.*" % path['path'])
  File "/usr/local/lib/python2.7/dist-packages/cyanite_utils/CyanitePaths.py", line 50, in printpaths
    self.printpaths("%s.*" % path['path'])
  File "/usr/local/lib/python2.7/dist-packages/cyanite_utils/CyanitePaths.py", line 50, in printpaths
    self.printpaths("%s.*" % path['path'])
  File "/usr/local/lib/python2.7/dist-packages/cyanite_utils/CyanitePaths.py", line 50, in printpaths
    self.printpaths("%s.*" % path['path'])
  File "/usr/local/lib/python2.7/dist-packages/cyanite_utils/CyanitePaths.py", line 50, in printpaths
    self.printpaths("%s.*" % path['path'])
  File "/usr/local/lib/python2.7/dist-packages/cyanite_utils/CyanitePaths.py", line 50, in printpaths
    self.printpaths("%s.*" % path['path'])
  File "/usr/local/lib/python2.7/dist-packages/cyanite_utils/CyanitePaths.py", line 50, in printpaths
    self.printpaths("%s.*" % path['path'])
  File "/usr/local/lib/python2.7/dist-packages/cyanite_utils/CyanitePaths.py", line 50, in printpaths
    self.printpaths("%s.*" % path['path'])
  File "/usr/local/lib/python2.7/dist-packages/cyanite_utils/CyanitePaths.py", line 48, in printpaths
    sys.stdout.flush()
IOError: [Errno 32] Broken pipe
```

**Comment by WrathOfChris** [comment]
Could you update to master?  Carbon-style rollups were added after I last cut a release, haven't gotten around to updating the pip package yet, sorry.  See: https://github.com/WrathOfChris/cyanite-utils/pull/13/files

**Comment by jippi** [comment]
can you bump pip? still seems to be an issue

**Comment by WrathOfChris** [comment]
Thanks for the reminder, I had neglected this.  Bumped 0.0.12.
