### ISSUE TITLE
"Connection refused" when taking to cyanite on anything other than localhost

### ISSUE THREAD

**Issue by craiggenner** [WrathOfChris/cyanite-utils#16]
```
Traceback (most recent call last):
  File "/usr/local/bin/cyanite-list", line 12, in <module>
    cli.cyanite_list()
  File "/usr/local/lib/python2.7/dist-packages/cyanite_utils/cli.py", line 29, in cyanite_list
    paths.printpaths('*')
  File "/usr/local/lib/python2.7/dist-packages/cyanite_utils/CyanitePaths.py", line 44, in printpaths
    paths = self.get(path)
  File "/usr/local/lib/python2.7/dist-packages/cyanite_utils/CyanitePaths.py", line 28, in get
    response = urllib2.urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 111] Connection refused>
```

Tracking this back to `Config.py` you get the following method:
```
    def httphost(self):
        return 'localhost'
```

Additionally nothing passed into the command line is used to override the cyanite port or host.

**Comment by aww-yiss** [comment]
I'm having the same kind of error with think, however I'm also using cyanite 0.5.1 and have the index stored in cassandra not elastic search. I think until these utils are updated to work with this, they aren't going to be compatible with the latest cyanite release.

**Comment by WrathOfChris** [comment]
Hi there, I'm not working with Cyanite at the moment, so haven't been following Pyr's updates.

Regarding @craiggenner original issue with localhost, that is an unfortunate trade-off of needing the live cyanite.yaml config file for knowledge of the rollups.

@aww-yiss probably won't have time in the near future to look at cassandra indexes, however I'll be happy to look at and merge patches to add features.

**Comment by sgran** [comment]
Hi,

The cyanite.yaml defines the http host - you don't need to hardcode it to localhost unless it's absent from the yaml file.

**Comment by WrathOfChris** [comment]
Fair point. I originally made the decision to hard-code this to localhost to provide a safe default - if you ran the utils against a remote host with incorrect or out-of-date rollup definitions it would not work as expected.

I'm not committed to that choice though, if you have a patch/pr I'll take a look.
